Feature/home component
Google-Developer-Student-Clubs-TUK/2022-G.A.G-Android pull request #15
Opened 2022-12-02 21:06 UTC by teawon

## 진행상황
- 기본 ui
- 다크모드, 라이트 모드에 따른 색상 변화
- 상단의 Statusbar색 변경
- 스크롤 추가
<img width="290" alt="스크린샷 2022-12-03 오전 5 59 09" src="https://user-images.githubusercontent.com/78795820/205385277-3ddc2184-9ddf-46e9-b469-6f35af6dfb09.png">
<img width="290" alt="스크린샷 2022-12-03 오전 5 11 27" src="https://user-images.githubusercontent.com/78795820/205385283-2671c230-f43a-4692-bfb4-3acc6a7bec61.png">

## 질문사항 및 ETC
-  다크모드 여부에 따라 가장자리 border를 그리는 부분은 광무님이 구현하신 코드를 참고했습니다. 다만 반복적으로 사용되서 따로 모듈로 분리하면 좋겠다고 생각했는데요 의미상 Theme쪽에다가 color처럼 다크모드 여부를 확인해서 modifier를 변수로 저장하고 싶었는데
`MaterialTheme(
        colors = colors,
        typography = Typography,
        shapes = Shapes,
        content = content
    )`
에서는 Modifier변수타입을 넣을 수 없어서 고민을 하다가 supports부분에 따로 넣어서 사용했습니다.
이런식으로 분리해도 괜찮은지? 의견이 듣고싶습니다.

- 최상단의 statusBar의 색깔을 조절하기 위해 아래 컴포넌트를 따로 분리해서 생성했습니다.
  `@Composable
  fun statusBarColor(systemUiController : SystemUiController , color :Color) {
      if(isSystemInDarkTheme()){
          systemUiController.setSystemBarsColor(
              color = color
          )
      }else{
          systemUiController.setSystemBarsColor(
              color = color
          )
      }
  }`

  사용할 Screen에서 원하는 색을 매개변수로 던져주면 상단의 색이 바뀌는데 사실 코드상에서는 다크모드이든 아니든 모두 같은 색을 나타내면 되기 때문에 처음에는 ` systemUiController.setSystemBarsColor(
              color = color
          )` 코드만 넣었었는데 이렇게 하게되면 색이 바뀌지 않습니다.. (???? 분명 if문을 넣든 아니든 값이 바뀌어야하는게아닌가요 ㅜ)
  
  여기서 질문드리고싶은 부분은 이런식으로 모듈 분리를 한게 괜찮은지, 그리고 왜 if문을 넣지 않으면 값이 바뀌지 않는지 아무리 고민해도 원인을 찾을 수없어 일단 코드 올려봅니다.

2022-12-05 06:42 UTC, kisa002 commented
1. Modifier변수타입을 넣을 수 없어서 고민을 하다가 supports부분에 따로 넣어서 사용했습니다.
   - 네 괜찮습니다. 추가적으로 Extension으로 만든다면 코틀린 언어의 특징을 잘 활용할 수 있습니다.

Before
```kotlin
Composable
fun drawBorder(): Modifier {
  return if (isSystemInDarkTheme()) Modifier else Modifier.border(
      width = 1.dp,
      color = MaterialTheme.colors.secondaryVariant,
      shape = RoundedCornerShape(12.dp)
  )
}
```
After
```kotlin
Composable
fun Modifier.drawBorder() = if (isSystemInDarkTheme()) Modifier else Modifier.border(
    width = 1.dp,
    color = MaterialTheme.colors.secondaryVariant,
    shape = RoundedCornerShape(12.dp)
)
```

2. 여기서 질문드리고싶은 부분은 이런식으로 상단bar 색을 바꿔도 괜찮은지, 그리고 왜 if문을 넣지 않으면 값이 바뀌지 않는지 아무리 고민해도 원인을 찾을 수없어 일단 코드 올려봅니다.
   - 음... 질문과 시나리오가 잘 이해가 가지 않아 추가적인 설명이 필요할 것 같습니다. (스크린샷 혹은 시나리오 영상)
우선 색상을 변경하는 함수를 공통으로 사용할 수 있게 빼는 것도 좋습니다만 굳이 분리하신 이유가 있으실까요?

2022-12-05 06:43 UTC, kisa002 commented
제 코드들이 많이 섞여있기에 rebase를 하면 좋을 것 같군요!

2022-12-05 07:15 UTC, kisa002 requested changes
수정 필요 사항과 피드백 몇 가지 작성하였습니다 😄

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/supports/drawBorder.kt
> +fun drawBorder(): Modifier {
Modifier.drawBorder 이렇게 확장 함수로 구현 가능합니다.

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +
createRefs를 활용하면 변수를 각각 선언/정의하지 않고 한번에 정의할 수 있습니다.
추가적으로 Reference임을 알 수 있게 변수뒤에 ref를 붙임으로써 가독성을 높일 수 있을 것이라 생각됩니다!

ex
```kotlin
val (profileRef, contentRef, nextTimetableRef) = createRefs()
```

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +            .background(MaterialTheme.colors.surface)
background에서 color와 shape를 지정하는 것이 아닌, clip과 background를 분리하신 이유가 있으실까요?

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +            )
then은 체이닝을 걸어주는 녀석으로 보통 조건문 사용 시 많이 활용됩니다.
ex
```kotlin
Modifier.then(if (isError) Modifier.backround(color = Color.Red) else Modifier)
```
위의 코드에서는 반드시 실행되어야하는 함수임에도 then을 사용하셨는데 어떤 의도인지 궁금합니다!

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +            )
아 자답합니다. drawBorder 함수가 extension이 아니기에 then안에서 실행하신 것으로 추측됩니다.
drawBorder 함수를 extension으로 사용하신다면 then을 생략하시고 바로 사용하실 수 있습니다 :)

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +                .padding(20.dp),
이러한 부분들도 drawBorder 함수를 extension으로 refactor 및 then 생략하는 방식을 고려해보시면 좋을 것 같습니다!

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    SchoolmateTheme {
각 컴포저블에 마다 `SchoolmateTheme`를 사용하고 계시는데 이유가 있으실까요?

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeViewModel.kt
> +    val todoInfo = _todoInfo
캡슐화를 의도하신 것이라면 아래와 같이 Mutable/State를 지정해주셔야 은닉화가 가능합니다

```kotlin
private val _data: MutableState<String> = mutableStateOf("")
val data: MutableState<String> = data
```

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    statusBarColor(rememberSystemUiController() , Color.Transparent)
composable 내부에 함수를 바로 넣으면 recomposition이 발생할 때 마다 해당 함수가 지속적으로 실행되게 됩니다. LaunchedEffect를 사용하지 않는 이유는 무엇일까요?

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    viewModel.getData()
이 부분은 테스트를 위해 recomposition 영역에 넣어둔 것 일까요?

2022-12-05 07:15 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +fun HomeScreen(viewModel: HomeViewModel) {
Hilt 라이브러리 사용 시, hiltViewModel를 사용하여 ViewModel을 주입받을 수 있습니다!
Ex
```kotlin
fun HomeScreen(viewModel: HomeViewModel = hiltViewModel()) {}
```

2022-12-05 13:38 UTC, teawon commented
> 

넵 이미 Rebase하고 진행중입니다!

2022-12-05 13:49 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +
한 줄로 줄어드니 코드가 줄고 가독성도 훨씬 올라가네요 좋은 피드백 감사드립니다!

2022-12-05 13:56 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/supports/drawBorder.kt
> +fun drawBorder(): Modifier {
답변 감사드립니다.
확장함수를 사용했을 때 코드의 간결성과 가독성이 높아지는 장점이 있다는데 
그럼 성능면에서는 관련이 없다고 봐도 괜찮을까요?

2022-12-05 14:08 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +            .background(MaterialTheme.colors.surface)
특별한 이유는 없는데 "둥글게 자르고 내부를 채워야겠다" 라는 방식으로 접근했던 것 같습니다.
틀을 잡는 행위 자체는 background 부분에서 일관적으로 모양과 색을 표현하는데 더 좋은 방법이라 한번에 표현하는게 더 좋겠죠?

피드백 수용해서 적용하겠습니다.

2022-12-05 14:15 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    SchoolmateTheme {
Theme.kt에서 정의한 MaterialTheme을 사용하려면 해당 composable로 감싸야만 사용가능하다고 생각했는데 착각이였네요!


`@Preview(uiMode = Configuration.UI_MODE_NIGHT_YES)
@Composable
private fun ArticleDetailDarkPreview() {
    SchoolmateTheme {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(MaterialTheme.colors.background)
        ) {
            ArticleDetailScreen()
        }
    }
}`

Preview쪽에서는 SchoolmateTheme이 사용되었는데 혹시 어떤 용도로 쓰이는지 설명해주실 수 있으신가요?

2022-12-05 14:46 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeViewModel.kt
> +    val todoInfo = _todoInfo
혹시 말씀해주신 State지정이 아래코드가 맞을까요?
`    private val _todoInfo : MutableState<List<TodoDto>> = mutableStateOf(listOf())
        val todoInfo : State<List<TodoDto>> = _todoInfo`
        
State를 통해 타입을 명시하지 않아도 자동으로 대입이 되는걸로 알고있는데 혹시 직접 지정했을 때와 지정하지 않았을때 차이가 무엇인가요?? (마우스를 올렸을 때 변수타입은 똑같이 나오긴 합니다!)
     
 그리고 위 코드대로 State를 지정하면 `java.lang.NoSuchMethodError: No virtual method getTimeScheduleInfo()` 오류가 발생하며 프로그램이 죽어버립니다.
     
  확실히 차이가 있으니 죽어버리는 것 같은데 이유를 잘 모르겠습니다ㅜㅜ

2022-12-05 14:46 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    viewModel.getData()
넵 맞습니다!

2022-12-05 14:49 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/supports/drawBorder.kt
> +fun drawBorder(): Modifier {
네 오히려 확장함수를 사용하게 되면 불필요한 곳에서의 사용을 방지할 수 있습니다 😸

2022-12-05 14:51 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    SchoolmateTheme {
Theme의 경우 최상위에서 선언하면 아래의 컴포넌트들 모두 적용되게 됩니다!
Preview의 경우 최상위에서 호출되는 곳이 없기에 Theme를 넣어주고 있습니다!

2022-12-05 14:51 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeViewModel.kt
> +    val todoInfo = _todoInfo
엇 런타임에서 죽게 되나요? 흠...

2022-12-05 14:59 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    statusBarColor(rememberSystemUiController() , Color.Transparent)
지능이 부족해서 그런것같습니다

2022-12-05 16:36 UTC, teawon commented
@kisa002 
피드백 정리해서 수정했습니다! 괜찮으시면 merge진행하겠습니다

2022-12-06 04:27 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    statusBarColor(rememberSystemUiController() , Color.Transparent)
@teawon 엌ㅋㅋㅋㅋㅋㅋㅋ 앙대요!!

2022-12-08 03:25 UTC, kisa002 approved these changes

2022-12-08 03:25 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +
의미없는 라인 개행!!

2022-12-08 03:25 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +
의믜 없는!!

2022-12-08 03:25 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +
라인 개행!!

2022-12-08 03:25 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
remember도 하나의 방법이지요

2022-12-08 05:18 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +
앗 좋은 지적감사합니다 ㅎㅎ..

2022-12-08 05:21 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
전체 Todo데이터를 foreach문으로 반복하는 내부요소에서 제출여부에 따라 보여지는 동그라미의 색을 바꾸고자 선언한 코드입니다.
이 상황에서는 remember를 사용하지 않아도 괜찮지 않나용ㅇ?

2022-12-08 06:56 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
주관적인 판단이 들어갈 것 같네요
recomposition scope가 해당 범위까지 들어가는지 확인해야겠지만, is_submit이 변경되지 않았음에도 매 프레임마다 비교하는건 큰 영향을 끼치진 않지만 개인적으로는 방지할 것 같긴 합니다!

2022-12-08 06:56 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
색상은 Color에 정의해두었으니, DeepBlue와 Orange 사용하시면 됩니다!

2022-12-08 07:42 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
> 주관적인 판단이 들어갈 것 같네요 recomposition scope가 해당 범위까지 들어가는지 확인해야겠지만, is_submit이 변경되지 않았음에도 매 프레임마다 비교하는건 큰 영향을 끼치진 않지만 개인적으로는 방지할 것 같긴 합니다!

오호.. 그런 관점에서 바라볼 수도 있겠네요. 
그런데 api를 통해 가져오는 데이터가 같다면 어처피 recomposition이 발생하지 않지 않나요?

2022-12-08 07:45 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
아 만약에 사용자가 하나의 TodoList데이터를 추가하게된다면 데이터에 변화가 생겨 TodoList데이터를 받아오는 composible에서 다시 recomposition이 일어나는데 이 때 색부분이라도 recomposition이 발생하지 않도록 remember를 사용하는거군요!

색 변화는 짧은 시간이지만 만약에 submit여부에 따라 복잡한 로직을 처리한다면 더더욱 remember를 사용하야하겠네요??
근데 기존의 text부분에는 remember를 넣지 않는 이유는 text를 다시 그리는건 간단하기때문인가요?

2022-12-08 13:45 UTC, kisa002 commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
음 해당 TodoList 함수에 로그 찍게 해두고 화면 스크롤 시 로그가 찍히는지 확인해보시겠어요?

2022-12-08 15:29 UTC, teawon commented on presentaion/src/main/java/com/haeyum/schoolmate/ui/main/home/HomeScreen.kt
> +    val color = if (data.is_submit) Color(0xFF3C5CFF) else Color(0xFFFF5C17)
예상대로 처음에만 로그가 찍히고 스크롤을 할때 추가적인 로그가 찍히지는 않습니다!

2022-12-09 04:17 UTC, merged